In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [193]:
df = pd.read_csv('autos.csv', encoding = 'cp1252')

In [5]:
df.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [6]:
df.describe()

,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,nrOfPictures,postalCode
count,3.715280e+05,371528.000000,371528.000000,371528.000000,371528.000000,371528.0,371528.00000
mean,1.729514e+04,2004.577997,115.549477,125618.688228,5.734445,0.0,50820.66764
std,3.587954e+06,92.866598,192.139578,40112.337051,3.712412,0.0,25799.08247
min,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.00000
25%,1.150000e+03,1999.000000,70.000000,125000.000000,3.000000,0.0,30459.00000
50%,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,0.0,49610.00000
75%,7.200000e+03,2008.000000,150.000000,150000.000000,9.000000,0.0,71546.00000
max,2.147484e+09,9999.000000,20000.000000,150000.000000,12.000000,0.0,99998.00000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 20 columns):
dateCrawled            371528 non-null object
name                   371528 non-null object
seller                 371528 non-null object
offerType              371528 non-null object
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      299468 non-null object
dateCreated            371528 non-null object
nrOfPictures           371528 non-null int64
postalCode             371528 non-null int64
lastSeen               371528 non-null object
dtypes: int64(7), object(13)
memory usage: 56.7+ MB

In [9]:
df.isnull().sum()

dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [104]:
df.name.unique().size

233531

In [194]:
df.drop(['name', 'nrOfPictures'], axis=1, inplace = True)

In [14]:
df.seller.unique()

array(['privat', 'gewerblich'], dtype=object)

In [16]:
df.groupby('seller').size()

seller
gewerblich         3
privat        371525
dtype: int64

In [21]:
df.groupby('offerType').size()

offerType
Angebot    371516
Gesuch         12
dtype: int64

In [23]:
df.groupby('model').size()

model
100              417
145               50
147              572
156              629
159              212
1_reihe         1306
1er             3837
200               18
2_reihe         4816
300c             148
3_reihe         3503
3er            20567
4_reihe          640
500              927
5_reihe          451
5er             8546
601              419
6_reihe         1291
6er              258
7er             1143
80              1606
850              212
90               104
900              117
9000              31
911              954
a1               622
a2               373
a3              6604
a4             10257
               ...
toledo           343
touareg          745
touran          3540
transit          764
transporter     5528
tt              1325
tucson           239
twingo          4953
up               348
v40              782
v50              255
v60               48
v70              645
v_klasse         168
vectra          4255
verso            312
viano            423
vito             914
vivaro           343
voyager          343
wrangler         165
x_reihe         2307
x_trail          216
x_type           177
xc_reihe         338
yaris           1034
yeti             199
ypsilon          209
z_reihe          890
zafira          3049
dtype: int64

In [195]:
df = df[(df['yearOfRegistration'] >= 1950) & (df['yearOfRegistration'] <= 2017)]

In [107]:
len(df)

367105

In [196]:
df = df[(df['powerPS']) > 20 & (df['powerPS'] < 500)]

In [109]:
df.describe()

,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,postalCode
count,3.275520e+05,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000
mean,1.673540e+04,2003.427050,129.873651,125632.143904,5.955598,51374.887868
std,3.794385e+06,7.079072,197.014712,39339.653489,3.599735,25816.123386
min,0.000000e+00,1950.000000,1.000000,5000.000000,0.000000,1067.000000
25%,1.300000e+03,1999.000000,80.000000,100000.000000,3.000000,31020.000000
50%,3.300000e+03,2004.000000,116.000000,150000.000000,6.000000,50374.000000
75%,7.800000e+03,2008.000000,150.000000,150000.000000,9.000000,72270.000000
max,2.147484e+09,2017.000000,20000.000000,150000.000000,12.000000,99998.000000

In [178]:
df.isnull().sum()

dateCrawled                0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            20017
yearOfRegistration         0
gearbox                 6423
powerPS                    0
model                  13629
kilometer                  0
monthOfRegistration        0
fuelType               20208
brand                      0
notRepairedDamage      49282
dateCreated                0
postalCode                 0
lastSeen                   0
dtype: int64

In [197]:
df = df.dropna(thresh = 13)
df.isnull().sum()
len(df)

327552

In [146]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [198]:
df['gearbox'].fillna(value='not declared', inplace=True)
df['model'].fillna(value='not declared', inplace=True)
df['fuelType'].fillna(value='not declared', inplace=True)
df['notRepairedDamage'].fillna(value='not declared', inplace=True)
df['vehicleType'].fillna(value='not declared', inplace=True)

In [199]:
df.isnull().sum()

dateCrawled            0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
postalCode             0
lastSeen               0
dtype: int64

In [202]:
dates = pd.DatetimeIndex(df['dateCrawled'])
years = pd.DataFrame(dates.year)
df['dateCrawled'] = years[0]
df

,dateCrawled,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen
1,2016.0,privat,Angebot,18300,test,coupe,2011,manuell,190,not declared,125000,5,diesel,audi,ja,2016-03-24 00:00:00,66954,2016-04-07 01:46:50
2,2016.0,privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,not declared,2016-03-14 00:00:00,90480,2016-04-05 12:47:46
3,2016.0,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,91074,2016-03-17 17:40:17
4,2016.0,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,60437,2016-04-06 10:17:21
5,2016.0,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,33775,2016-04-06 19:17:07
6,2016.0,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,67112,2016-04-05 18:18:39
7,2016.0,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,19348,2016-03-25 16:47:58
8,2016.0,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,not declared,2016-04-04 00:00:00,94505,2016-04-04 23:42:13
9,2016.0,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,not declared,volkswagen,not declared,2016-03-17 00:00:00,27472,2016-03-31 17:17:06
10,2016.0,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,96224,2016-04-06 10:45:34
11,2016.0,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,57290,2016-04-07 10:25:17
12,2016.0,privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,not declared,2016-03-15 00:00:00,37269,2016-04-01 13:16:16
13,2016.0,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,not declared,volkswagen,nein,2016-03-21 00:00:00,90762,2016-03-23 02:50:54
14,2016.0,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,4177,2016-04-06 07:45:42
16,2016.0,privat,Angebot,300,test,not declared,2016,not declared,60,polo,150000,0,benzin,volkswagen,not declared,2016-04-01 00:00:00,38871,2016-04-01 12:46:46
17,2016.0,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,65599,2016-04-06 13:16:07
18,2016.0,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,88361,2016-04-05 18:45:11
19,2016.0,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,49565,2016-04-05 22:46:05
20,2016.0,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,75365,2016-04-05 16:45:49
21,2016.0,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,68309,2016-04-07 06:44:26
23,2016.0,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,9526,2016-03-21 01:46:11
24,2016.0,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,35390,2016-03-13 20:40:49
25,2016.0,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,73765,2016-03-18 21:44:09
26,2016.0,privat,Angebot,5555,control,not declared,2017,manuell,125,c4,125000,4,not declared,citroen,nein,2016-03-10 00:00:00,31139,2016-03-16 09:16:46
27,2016.0,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,12621,2016-03-26 09:44:53
28,2016.0,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,87471,2016-03-10 07:44:33
29,2016.0,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,86199,2016-03-09 11:45:28
30,2016.0,privat,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016-04-03 00:00:00,53879,2016-04-05 15:16:05
31,2016.0,privat,Angebot,899,control,not declared,2016,manuell,60,clio,150000,6,benzin,renault,not declared,2016-03-29 00:00:00,37075,2016-03-29 17:43:07
33,2016.0,privat,Angebot,18000,test,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,2016-03-25 00:00:00,39179,2016-04-07 04:45:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371491,NaN,privat,Angebot,3200,test,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,2016-03-15 00:00:00,60439,2016-04-07 03:16:40
371494,NaN,privat,Angebot,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,not declared,2016-03-26 00:00:00,4107,2016-04-06 20:45:16
371496,NaN,privat,Angebot,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,not declared,peugeot,nein,2016-03-20 00:00:00,53947,2016-03-26 21:18:23
371497,NaN,privat,Angebot,4900,control,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,2016-03-05 00:00:00,88213,2016-04-05 18:44:48
371498,NaN,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,not declared,2016-03-11 00:00:00,65936,2016-03-17 12:44:29
371499,NaN,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,24850,2016-03-13 00:16:40
371500,NaN,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,38470,2016-04-07 04:17:32
371501,NaN,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,34320,2016-04-06 09:16:04
371502,NaN,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,34414,2016-04-07 09:44:29
371503,NaN,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,90439,2016-04-07 04:16:26
371505,NaN,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,58730,2016-04-05 20:45:39
371506,NaN,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,1217,2016-04-07 02:44:27
371507,NaN,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,not declared,2016-03-16 00:00:00,56472,2016-03-18 11:30:17
371508,NaN,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,23820,2016-04-06 15:18:04
371509,NaN,privat,Angebot,1900,test,not declared,2000,manuell,110,not declared,150000,7,not declared,volkswagen,nein,2016-03-11 00:00:00,87700,2016-03-12 14:16:51
371510,NaN,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,60437,2016-03-12 12:18:05
371511,NaN,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,4275,2016-04-06 12:46:41
371512,NaN,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,90473,2016-04-07 00:44:51
371513,NaN,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,45896,2016-04-06 15:45:01
371514,NaN,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,not declared,2016-04-04 00:00:00,88477,2016-04-06 12:44:52
371515,NaN,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,not declared,2016-03-09 00:00:00,18246,2016-04-04 08:15:30
371516,NaN,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,48653,2016-04-06 11:17:13
371517,NaN,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,75223,2016-04-02 18:16:20
371518,NaN,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,81825,2016-04-06 20:47:12
371519,NaN,privat,Angebot,5250,control,not declared,2016,automatik,150,159,150000,12,not declared,alfa_romeo,nein,2016-03-09 00:00:00,51371,2016-03-13 01:44:13
371520,NaN,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,96465,2016-03-19 20:44:43
371524,NaN,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,26135,2016-03-11 18:17:12
371525,NaN,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,87439,2016-04-07 07:15:26
371526,NaN,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,not declared,2016-03-20 00:00:00,40764,2016-03-24 12:45:21
371527,NaN,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,73326,2016-03-22 03:17:10

In [204]:
dates = pd.DatetimeIndex(df['dateCreated'])
years = pd.DataFrame(dates.year)
df['dateCreated'] = years[0]
df

,dateCrawled,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen
1,2016.0,privat,Angebot,18300,test,coupe,2011,manuell,190,not declared,125000,5,diesel,audi,ja,2016.0,66954,2016.0
2,2016.0,privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,not declared,2016.0,90480,2016.0
3,2016.0,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016.0,91074,2016.0
4,2016.0,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016.0,60437,2016.0
5,2016.0,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016.0,33775,2016.0
6,2016.0,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016.0,67112,2016.0
7,2016.0,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016.0,19348,2016.0
8,2016.0,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,not declared,2016.0,94505,2016.0
9,2016.0,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,not declared,volkswagen,not declared,2016.0,27472,2016.0
10,2016.0,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016.0,96224,2016.0
11,2016.0,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016.0,57290,2016.0
12,2016.0,privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,not declared,2016.0,37269,2016.0
13,2016.0,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,not declared,volkswagen,nein,2016.0,90762,2016.0
14,2016.0,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016.0,4177,2016.0
16,2016.0,privat,Angebot,300,test,not declared,2016,not declared,60,polo,150000,0,benzin,volkswagen,not declared,2016.0,38871,2016.0
17,2016.0,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016.0,65599,2016.0
18,2016.0,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016.0,88361,2016.0
19,2016.0,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016.0,49565,2016.0
20,2016.0,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016.0,75365,2016.0
21,2016.0,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016.0,68309,2016.0
23,2016.0,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016.0,9526,2016.0
24,2016.0,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016.0,35390,2016.0
25,2016.0,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016.0,73765,2016.0
26,2016.0,privat,Angebot,5555,control,not declared,2017,manuell,125,c4,125000,4,not declared,citroen,nein,2016.0,31139,2016.0
27,2016.0,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016.0,12621,2016.0
28,2016.0,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016.0,87471,2016.0
29,2016.0,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016.0,86199,2016.0
30,2016.0,privat,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016.0,53879,2016.0
31,2016.0,privat,Angebot,899,control,not declared,2016,manuell,60,clio,150000,6,benzin,renault,not declared,2016.0,37075,2016.0
33,2016.0,privat,Angebot,18000,test,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,2016.0,39179,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371491,NaN,privat,Angebot,3200,test,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,NaN,60439,NaN
371494,NaN,privat,Angebot,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,not declared,NaN,4107,NaN
371496,NaN,privat,Angebot,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,not declared,peugeot,nein,NaN,53947,NaN
371497,NaN,privat,Angebot,4900,control,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,NaN,88213,NaN
371498,NaN,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,not declared,NaN,65936,NaN
371499,NaN,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,NaN,24850,NaN
371500,NaN,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,NaN,38470,NaN
371501,NaN,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,NaN,34320,NaN
371502,NaN,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,NaN,34414,NaN
371503,NaN,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,NaN,90439,NaN
371505,NaN,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,NaN,58730,NaN
371506,NaN,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,NaN,1217,NaN
371507,NaN,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,not declared,NaN,56472,NaN
371508,NaN,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,NaN,23820,NaN
371509,NaN,privat,Angebot,1900,test,not declared,2000,manuell,110,not declared,150000,7,not declared,volkswagen,nein,NaN,87700,NaN
371510,NaN,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,NaN,60437,NaN
371511,NaN,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,NaN,4275,NaN
371512,NaN,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,NaN,90473,NaN
371513,NaN,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,NaN,45896,NaN
371514,NaN,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,not declared,NaN,88477,NaN
371515,NaN,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,not declared,NaN,18246,NaN
371516,NaN,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,NaN,48653,NaN
371517,NaN,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,NaN,75223,NaN
371518,NaN,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,NaN,81825,NaN
371519,NaN,privat,Angebot,5250,control,not declared,2016,automatik,150,159,150000,12,not declared,alfa_romeo,nein,NaN,51371,NaN
371520,NaN,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,NaN,96465,NaN
371524,NaN,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,NaN,26135,NaN
371525,NaN,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,NaN,87439,NaN
371526,NaN,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,not declared,NaN,40764,NaN
371527,NaN,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,NaN,73326,NaN

In [205]:
df['age'] = df['dateCreated'] - df['yearOfRegistration']
df

,dateCrawled,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen,age
1,2016.0,privat,Angebot,18300,test,coupe,2011,manuell,190,not declared,125000,5,diesel,audi,ja,2016.0,66954,2016.0,5.0
2,2016.0,privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,not declared,2016.0,90480,2016.0,12.0
3,2016.0,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016.0,91074,2016.0,15.0
4,2016.0,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016.0,60437,2016.0,8.0
5,2016.0,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016.0,33775,2016.0,21.0
6,2016.0,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016.0,67112,2016.0,12.0
7,2016.0,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016.0,19348,2016.0,36.0
8,2016.0,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,not declared,2016.0,94505,2016.0,2.0
9,2016.0,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,not declared,volkswagen,not declared,2016.0,27472,2016.0,18.0
10,2016.0,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016.0,96224,2016.0,12.0
11,2016.0,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016.0,57290,2016.0,11.0
12,2016.0,privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,not declared,2016.0,37269,2016.0,21.0
13,2016.0,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,not declared,volkswagen,nein,2016.0,90762,2016.0,12.0
14,2016.0,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016.0,4177,2016.0,5.0
16,2016.0,privat,Angebot,300,test,not declared,2016,not declared,60,polo,150000,0,benzin,volkswagen,not declared,2016.0,38871,2016.0,0.0
17,2016.0,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016.0,65599,2016.0,12.0
18,2016.0,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016.0,88361,2016.0,9.0
19,2016.0,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016.0,49565,2016.0,12.0
20,2016.0,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016.0,75365,2016.0,7.0
21,2016.0,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016.0,68309,2016.0,14.0
23,2016.0,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016.0,9526,2016.0,19.0
24,2016.0,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016.0,35390,2016.0,26.0
25,2016.0,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016.0,73765,2016.0,14.0
26,2016.0,privat,Angebot,5555,control,not declared,2017,manuell,125,c4,125000,4,not declared,citroen,nein,2016.0,31139,2016.0,-1.0
27,2016.0,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016.0,12621,2016.0,8.0
28,2016.0,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016.0,87471,2016.0,35.0
29,2016.0,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016.0,86199,2016.0,13.0
30,2016.0,privat,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016.0,53879,2016.0,21.0
31,2016.0,privat,Angebot,899,control,not declared,2016,manuell,60,clio,150000,6,benzin,renault,not declared,2016.0,37075,2016.0,0.0
33,2016.0,privat,Angebot,18000,test,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,2016.0,39179,2016.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371491,NaN,privat,Angebot,3200,test,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,NaN,60439,NaN,NaN
371494,NaN,privat,Angebot,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,not declared,NaN,4107,NaN,NaN
371496,NaN,privat,Angebot,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,not declared,peugeot,nein,NaN,53947,NaN,NaN
371497,NaN,privat,Angebot,4900,control,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,NaN,88213,NaN,NaN
371498,NaN,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,not declared,NaN,65936,NaN,NaN
371499,NaN,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,NaN,24850,NaN,NaN
371500,NaN,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,NaN,38470,NaN,NaN
371501,NaN,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,NaN,34320,NaN,NaN
371502,NaN,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,NaN,34414,NaN,NaN
371503,NaN,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,NaN,90439,NaN,NaN
371505,NaN,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,NaN,58730,NaN,NaN
371506,NaN,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,NaN,1217,NaN,NaN
371507,NaN,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,not declared,NaN,56472,NaN,NaN
371508,NaN,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,NaN,23820,NaN,NaN
371509,NaN,privat,Angebot,1900,test,not declared,2000,manuell,110,not declared,150000,7,not declared,volkswagen,nein,NaN,87700,NaN,NaN
371510,NaN,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,NaN,60437,NaN,NaN
371511,NaN,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,NaN,4275,NaN,NaN
371512,NaN,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,NaN,90473,NaN,NaN
371513,NaN,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,NaN,45896,NaN,NaN
371514,NaN,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,not declared,NaN,88477,NaN,NaN
371515,NaN,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,not declared,NaN,18246,NaN,NaN
371516,NaN,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,NaN,48653,NaN,NaN
371517,NaN,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,NaN,75223,NaN,NaN
371518,NaN,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,NaN,81825,NaN,NaN
371519,NaN,privat,Angebot,5250,control,not declared,2016,automatik,150,159,150000,12,not declared,alfa_romeo,nein,NaN,51371,NaN,NaN
371520,NaN,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,NaN,96465,NaN,NaN
371524,NaN,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,NaN,26135,NaN,NaN
371525,NaN,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,NaN,87439,NaN,NaN
371526,NaN,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,not declared,NaN,40764,NaN,NaN
371527,NaN,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,NaN,73326,NaN,NaN

In [206]:
targets = df['price']
features = df
del features['price']

In [207]:
targets = pd.DataFrame(targets)
targets.columns = ['price']
targets

        price
1       18300
2        9800
3        1500
4        3600
5         650
6        2200
7           0
8       14500
9         999
10       2000
11       2799
12        999
13       2500
14      17999
16        300
17       1750
18       7550
19       1850
20      10400
21       3699
23        450
24        500
25       2500
26       5555
27       6900
28       1990
29        690
30       3300
31        899
33      18000
...       ...
371491   3200
371494  11500
371496   3850
371497   4900
371498    699
371499    600
371500  20400
371501   3900
371502   1600
371503   1700
371505    800
371506   5900
371507   5999
371508   1400
371509   1900
371510   6500
371511   1999
371512   5000
371513   4400
371514    999
371515   1690
371516   1490
371517   7900
371518   3999
371519   5250
371520   3200
371524   1199
371525   9200
371526   3400
371527  28990

[327552 rows x 1 columns]

In [209]:
for cols in df.columns:
    df[cols] = LabelEncoder().fit_transform(df[cols])
df.describe()

,dateCrawled,seller,offerType,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen,age
count,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000,327552.000000
mean,2281.758173,0.999994,0.000012,0.518098,4.612758,53.427050,0.800795,125.297009,103.037933,10.475390,5.955598,2.055893,20.532386,1.054684,2282.758099,3673.354893,2281.758173,2301.632660
std,7321.615956,0.002471,0.003495,0.499673,1.828651,7.079072,0.445804,63.081694,71.541722,2.814358,3.599735,1.646293,13.447290,0.493191,7321.615978,2027.010456,7321.615956,7336.311087
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,4.000000,49.000000,1.000000,79.000000,40.000000,10.000000,3.000000,1.000000,9.000000,1.000000,1.000000,2161.000000,0.000000,10.000000
50%,0.000000,1.000000,0.000000,1.000000,5.000000,54.000000,1.000000,115.000000,103.000000,12.000000,6.000000,1.000000,23.000000,1.000000,1.000000,3484.000000,0.000000,15.000000
75%,0.000000,1.000000,0.000000,1.000000,6.000000,58.000000,1.000000,149.000000,163.000000,12.000000,9.000000,3.000000,33.000000,1.000000,1.000000,5023.000000,0.000000,20.000000
max,38662.000000,1.000000,1.000000,1.000000,8.000000,67.000000,2.000000,790.000000,250.000000,12.000000,12.000000,7.000000,39.000000,2.000000,38663.000000,8131.000000,38662.000000,38729.000000

In [211]:
from sklearn.preprocessing import scale

In [212]:
del df['dateCrawled']
del df['yearOfRegistration']
del df['monthOfRegistration']
del df['dateCreated']

In [214]:
features_scaled = pd.DataFrame(scale(features))
features_scaled

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.002471,-0.003495,0.964436,-0.881940,0.446845,1.009851,0.838143,0.186405,0.573475,-1.452517,-2.138496,0.459616,-0.311647,-0.312914
1,0.002471,-0.003495,0.964436,1.852320,-1.796297,0.581834,0.223116,0.186405,0.573475,-0.485778,1.916738,1.632774,-0.311647,-0.311960
2,0.002471,-0.003495,0.964436,-0.335088,0.446845,-0.813185,0.209138,0.541726,-0.641377,1.298971,-0.110879,1.652508,-0.311647,-0.311551
3,0.002471,-0.003495,0.964436,-0.335088,0.446845,-0.908300,-0.000530,-0.524238,0.573475,0.778419,-0.110879,0.260801,-0.311647,-0.312505
4,0.002471,-0.003495,0.964436,0.758616,0.446845,-0.385168,-1.286495,0.541726,-0.641377,-1.378152,-2.138496,-0.642501,-0.311647,-0.310733
5,0.002471,-0.003495,0.964436,-1.428792,0.446845,-0.274201,-1.328429,0.541726,-0.641377,0.332232,-0.110879,0.469976,-0.311647,-0.311960
6,0.002471,-0.003495,0.964436,0.758616,0.446845,-1.209497,-0.881137,-2.300845,-0.641377,1.298971,-0.110879,-1.242894,-0.311647,-0.308689
7,0.002471,-0.003495,-1.036875,-1.975643,0.446845,-0.020561,-0.587601,-2.656166,-0.641377,-0.783236,1.916738,1.905097,-0.311647,-0.313323
8,0.002471,-0.003495,0.964436,-0.335088,0.446845,-0.401020,0.209138,0.541726,3.003181,1.298971,1.916738,-0.855130,-0.311647,-0.311142
9,0.002471,-0.003495,-1.036875,0.758616,0.446845,-0.337610,-1.300473,0.541726,-0.641377,-0.113955,-0.110879,2.007218,-0.311647,-0.311960
10,0.002471,-0.003495,-1.036875,0.211764,0.446845,0.217226,0.963943,0.541726,0.573475,1.298971,-2.138496,0.175947,-0.311647,-0.312096
11,0.002471,-0.003495,-1.036875,0.211764,0.446845,-0.179086,0.963943,0.541726,-0.641377,1.298971,1.916738,-0.491540,-0.311647,-0.310733
12,0.002471,-0.003495,-1.036875,0.211764,0.446845,0.074554,0.963943,0.541726,3.003181,1.298971,-0.110879,1.648068,-0.311647,-0.311960
13,0.002471,-0.003495,-1.036875,1.852320,0.446845,1.009851,0.810187,-1.234880,0.573475,0.183503,-0.110879,-1.722912,-0.311647,-0.312914
14,0.002471,-0.003495,0.964436,1.305468,2.689987,-1.050972,1.005877,0.541726,-0.641377,1.298971,1.916738,-0.407672,-0.311647,-0.313596
15,0.002471,-0.003495,-1.036875,-0.335088,-1.796297,-0.813185,1.746705,0.541726,-0.641377,0.480961,-0.110879,0.396469,-0.311647,-0.311960
16,0.002471,-0.003495,0.964436,-1.975643,0.446845,0.153817,-0.587601,0.541726,0.573475,-0.783236,-0.110879,1.532133,-0.311647,-0.312369
17,0.002471,-0.003495,0.964436,-1.975643,0.446845,-0.385168,-0.978982,0.541726,-0.641377,-0.039591,-0.110879,-0.123016,-0.311647,-0.311960
18,0.002471,-0.003495,-1.036875,-0.881940,0.446845,0.534276,1.369302,-0.168916,-0.641377,1.298971,-0.110879,0.863167,-0.311647,-0.312642
19,0.002471,-0.003495,0.964436,0.758616,-1.796297,1.659802,-1.230584,0.541726,-0.641377,-1.378152,-0.110879,0.556310,-0.311647,-0.311687
20,0.002471,-0.003495,0.964436,-0.335088,0.446845,-1.209497,-0.853181,0.541726,-0.641377,0.704055,-0.110879,-1.511270,-0.311647,-0.311006
21,0.002471,-0.003495,0.964436,0.758616,0.446845,-0.131528,-0.881137,0.541726,-0.641377,-0.039591,-2.138496,-0.578861,-0.311647,-0.310052
22,0.002471,-0.003495,-1.036875,0.211764,-1.796297,1.057408,-1.230584,0.541726,0.573475,-1.378152,-2.138496,0.770419,-0.311647,-0.311687
23,0.002471,-0.003495,-1.036875,1.305468,0.446845,-0.020561,-0.629535,0.186405,3.003181,-1.155059,-0.110879,-0.734262,-0.311647,-0.313732
24,0.002471,-0.003495,0.964436,0.758616,0.446845,-0.432725,-0.405889,-1.590202,-0.641377,-0.708871,-0.110879,-1.443189,-0.311647,-0.312505
25,0.002471,-0.003495,0.964436,-1.975643,0.446845,-1.209497,1.704771,-3.722130,-0.641377,1.298971,-0.110879,1.459119,-0.311647,-0.308825
26,0.002471,-0.003495,0.964436,-0.335088,0.446845,-1.050972,1.047811,0.541726,-0.641377,-0.857601,-0.110879,1.359958,-0.311647,-0.311824
27,0.002471,-0.003495,0.964436,0.758616,-1.796297,-0.210791,-0.084397,0.541726,0.573475,-0.039591,-0.110879,-0.003135,-0.311647,-0.310733
28,0.002471,-0.003495,-1.036875,1.305468,0.446845,-1.050972,-0.377933,0.541726,-0.641377,0.480961,1.916738,-0.507820,-0.311647,-0.313596
29,0.002471,-0.003495,0.964436,0.758616,-1.796297,1.453720,-1.286495,-3.011487,-0.641377,-1.378152,-0.110879,-0.395339,-0.311647,-0.312369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327522,0.002471,-0.003495,0.964436,0.758616,0.446845,-0.163233,0.963943,0.541726,2.395754,1.298971,-0.110879,0.261787,1.450125,1.453644
327523,0.002471,-0.003495,-1.036875,0.758616,-1.796297,4.624217,-1.174672,0.186405,-0.641377,-1.378152,1.916738,-1.726365,1.450262,1.453780
327524,0.002471,-0.003495,0.964436,-1.428792,0.446845,-0.290053,-1.328429,0.186405,3.003181,0.332232,-0.110879,0.002292,1.450398,1.453916
327525,0.002471,-0.003495,-1.036875,0.211764,0.446845,-0.163233,-0.839203,0.541726,-0.641377,0.257868,-0.110879,1.519306,1.450535,1.454053
327526,0.002471,-0.003495,-1.036875,0.758616,0.446845,-0.401020,1.844550,0.541726,-0.641377,0.257868,1.916738,0.409296,1.450671,1.454189
327527,0.002471,-0.003495,-1.036875,-0.335088,0.446845,-1.146087,-0.266110,0.541726,-0.641377,0.257868,-0.110879,-1.011518,1.450808,1.454325
327528,0.002471,-0.003495,0.964436,0.758616,-1.796297,0.375751,0.209138,-2.656166,-0.641377,1.298971,-0.110879,-0.431846,1.450944,1.454462
327529,0.002471,-0.003495,0.964436,-1.975643,-1.796297,0.756211,1.914439,0.541726,-0.641377,-1.229423,-0.110879,-0.623261,1.451081,1.454598
327530,0.002471,-0.003495,0.964436,0.211764,0.446845,-0.020561,-1.034893,0.541726,-0.641377,-1.452517,-0.110879,-0.615368,1.451218,1.454734
327531,0.002471,-0.003495,-1.036875,-0.335088,0.446845,-0.924152,0.362895,-1.234880,-0.641377,1.001513,-0.110879,1.625867,1.451354,1.454871
327532,0.002471,-0.003495,0.964436,0.211764,0.446845,-0.401020,-0.839203,0.541726,-0.641377,0.257868,-2.138496,0.217880,1.449305,1.452826
327533,0.002471,-0.003495,0.964436,0.758616,0.446845,-0.337610,0.209138,0.541726,0.573475,1.298971,-0.110879,-1.804313,1.451491,1.455007
327534,0.002471,-0.003495,0.964436,0.211764,0.446845,0.217226,-1.034893,0.541726,0.573475,-1.452517,1.916738,0.139933,1.449169,1.452690
327535,0.002471,-0.003495,-1.036875,0.758616,0.446845,-0.020561,-0.839203,0.541726,-0.641377,0.257868,-0.110879,-1.094892,1.448896,1.452417
327536,0.002471,-0.003495,0.964436,1.305468,0.446845,-0.258348,0.838143,0.541726,3.003181,1.298971,-0.110879,1.486253,1.446847,1.450372
327537,0.002471,-0.003495,0.964436,0.758616,-1.796297,0.296489,-0.084397,0.541726,0.573475,-0.039591,-0.110879,0.260801,1.446984,1.450509
327538,0.002471,-0.003495,-1.036875,0.758616,0.446845,0.375751,-1.048871,0.541726,-0.641377,-1.452517,-0.110879,-1.718965,1.447120,1.450645
327539,0.002471,-0.003495,0.964436,0.758616,-1.796297,2.119524,-0.084397,0.541726,0.573475,-0.039591,-2.138496,1.631294,1.447257,1.450781
327540,0.002471,-0.003495,-1.036875,0.758616,0.446845,-0.337610,0.544607,0.541726,0.573475,0.704055,-0.110879,-0.235497,1.447393,1.450918
327541,0.002471,-0.003495,-1.036875,-1.428792,0.446845,-0.496135,0.670408,0.541726,-0.641377,0.480961,1.916738,1.547920,1.447530,1.451054
327542,0.002471,-0.003495,0.964436,0.211764,0.446845,-1.130235,-0.000530,0.541726,-0.641377,0.778419,1.916738,-1.280388,1.447666,1.451190
327543,0.002471,-0.003495,-1.036875,-0.335088,0.446845,-1.209497,0.586541,0.541726,-0.641377,1.298971,-0.110879,-0.154097,1.447803,1.451327
327544,0.002471,-0.003495,0.964436,0.758616,0.446845,0.217226,0.209138,0.541726,0.573475,1.298971,-0.110879,0.854780,1.447940,1.451463
327545,0.002471,-0.003495,0.964436,0.211764,0.446845,-1.954564,-1.286495,0.541726,0.573475,-1.378152,-0.110879,1.099476,1.448076,1.451599
327546,0.002471,-0.003495,-1.036875,1.305468,-1.796297,0.375751,-1.384340,0.541726,3.003181,-1.526881,-0.110879,-0.070229,1.448213,1.451736
327547,0.002471,-0.003495,-1.036875,0.758616,0.446845,1.564688,0.544607,0.541726,-0.641377,0.704055,-2.138496,2.023991,1.448349,1.451872
327548,0.002471,-0.003495,0.964436,-1.428792,-1.796297,-0.401020,0.069359,0.186405,-0.641377,0.852784,-0.110879,-0.915811,1.448486,1.452008
327549,0.002471,-0.003495,0.964436,-1.975643,0.446845,-0.385168,1.704771,0.541726,0.573475,1.298971,-0.110879,1.456159,1.448759,1.452281
327550,0.002471,-0.003495,0.964436,0.211764,0.446845,-0.416873,0.209138,0.541726,0.573475,1.298971,1.916738,-0.349458,3.208073,3.208071
327551,0.002471,-0.003495,-1.036875,0.758616,0.446845,3.023116,0.628474,-1.945523,-0.641377,-1.378152,-0.110879,0.734405,4.968889,4.965360