In [ ]:
import quandl
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn import model_selection

In [2]:
df = quandl.get('WIKI/GOOGL')

In [3]:
df

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2004-08-19,100.010,104.0600,95.9600,100.335,44659000.0,0.0,1.0,50.159839,52.191109,48.128568,50.322842,44659000.0
2004-08-20,101.010,109.0800,100.5000,108.310,22834300.0,0.0,1.0,50.661387,54.708881,50.405597,54.322689,22834300.0
2004-08-23,110.760,113.4800,109.0500,109.400,18256100.0,0.0,1.0,55.551482,56.915693,54.693835,54.869377,18256100.0
2004-08-24,111.240,111.6000,103.5700,104.870,15247300.0,0.0,1.0,55.792225,55.972783,51.945350,52.597363,15247300.0
2004-08-25,104.760,108.0000,103.8800,106.000,9188600.0,0.0,1.0,52.542193,54.167209,52.100830,53.164113,9188600.0
2004-08-26,104.950,107.9500,104.6600,107.910,7094800.0,0.0,1.0,52.637487,54.142132,52.492038,54.122070,7094800.0
2004-08-27,108.100,108.6200,105.6900,106.150,6211700.0,0.0,1.0,54.217364,54.478169,53.008633,53.239345,6211700.0
2004-08-30,105.280,105.4900,102.0100,102.010,5196700.0,0.0,1.0,52.802998,52.908323,51.162935,51.162935,5196700.0
2004-08-31,102.320,103.7100,102.1600,102.370,4917800.0,0.0,1.0,51.318415,52.015567,51.238167,51.343492,4917800.0
2004-09-01,102.700,102.9700,99.6700,100.250,9138200.0,0.0,1.0,51.509003,51.644421,49.989312,50.280210,9138200.0
2004-09-02,99.090,102.3700,98.9400,101.510,15118600.0,0.0,1.0,49.698414,51.343492,49.623182,50.912161,15118600.0
2004-09-03,100.950,101.7400,99.3200,100.010,5152400.0,0.0,1.0,50.631294,51.027517,49.813770,50.159839,5152400.0
2004-09-07,101.010,102.0000,99.6100,101.580,5847500.0,0.0,1.0,50.661387,51.157920,49.959219,50.947269,5847500.0
2004-09-08,100.740,103.0300,100.5000,102.300,4985600.0,0.0,1.0,50.525969,51.674514,50.405597,51.308384,4985600.0
2004-09-09,102.500,102.7100,101.0000,102.310,4061700.0,0.0,1.0,51.408694,51.514019,50.656371,51.313400,4061700.0
2004-09-10,101.470,106.5600,101.3000,105.330,8698800.0,0.0,1.0,50.892099,53.444980,50.806836,52.828075,8698800.0
2004-09-13,106.630,108.4100,106.4600,107.500,7844100.0,0.0,1.0,53.480088,54.372844,53.394825,53.916435,7844100.0
2004-09-14,107.440,112.0000,106.7900,111.490,10828900.0,0.0,1.0,53.886342,56.173402,53.560336,55.917612,10828900.0
2004-09-15,110.560,114.2300,110.2000,112.000,10713000.0,0.0,1.0,55.451172,57.291854,55.270615,56.173402,10713000.0
2004-09-16,112.340,115.8000,111.6500,113.970,9266300.0,0.0,1.0,56.343928,58.079285,55.997860,57.161452,9266300.0
2004-09-17,114.420,117.4900,113.5500,117.490,9472500.0,0.0,1.0,57.387149,58.926902,56.950802,58.926902,9472500.0
2004-09-20,116.950,121.6000,116.7700,119.360,10628700.0,0.0,1.0,58.656066,60.988265,58.565787,59.864797,10628700.0
2004-09-21,120.200,120.4200,117.5100,117.840,7228700.0,0.0,1.0,60.286097,60.396438,58.936933,59.102444,7228700.0
2004-09-22,117.450,119.6700,116.8100,118.380,7581200.0,0.0,1.0,58.906840,60.020277,58.585849,59.373280,7581200.0
2004-09-23,118.840,122.6300,117.0200,120.820,8535600.0,0.0,1.0,59.603992,61.504860,58.691174,60.597057,8535600.0
2004-09-24,120.970,124.1000,119.7600,119.830,9123400.0,0.0,1.0,60.672290,62.242136,60.065416,60.100525,9123400.0
2004-09-27,119.560,120.8800,117.8000,118.260,7066100.0,0.0,1.0,59.965107,60.627150,59.082382,59.313094,7066100.0
2004-09-28,121.150,127.4000,120.2100,126.860,16929000.0,0.0,1.0,60.762568,63.897245,60.291113,63.626409,16929000.0
2004-09-29,126.530,135.0200,126.2300,131.080,30516400.0,0.0,1.0,63.460898,67.719042,63.310433,65.742942,30516400.0
2004-09-30,129.899,132.3000,129.0000,129.600,13758000.0,0.0,1.0,65.150614,66.354831,64.699722,65.000651,13758000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-05-05,956.720,958.4395,948.0986,950.280,1593898.0,0.0,1.0,956.720000,958.439500,948.098600,950.280000,1593898.0
2017-05-08,947.450,960.9900,947.3950,958.690,1863198.0,0.0,1.0,947.450000,960.990000,947.395000,958.690000,1863198.0
2017-05-09,961.330,962.2000,954.4000,956.710,1633396.0,0.0,1.0,961.330000,962.200000,954.400000,956.710000,1633396.0
2017-05-10,956.220,956.7100,949.8400,954.840,1135809.0,0.0,1.0,956.220000,956.710000,949.840000,954.840000,1135809.0
2017-05-11,951.290,957.9900,948.6100,955.890,1016797.0,0.0,1.0,951.290000,957.990000,948.610000,955.890000,1016797.0
2017-05-12,957.850,957.9800,952.0600,955.140,1204133.0,0.0,1.0,957.850000,957.980000,952.060000,955.140000,1204133.0
2017-05-15,955.290,962.7000,952.8200,959.220,1314574.0,0.0,1.0,955.290000,962.700000,952.820000,959.220000,1314574.0
2017-05-16,963.550,965.8955,960.3500,964.610,1069898.0,0.0,1.0,963.550000,965.895500,960.350000,964.610000,1069898.0
2017-05-17,959.700,960.9900,940.0600,942.170,2414323.0,0.0,1.0,959.700000,960.990000,940.060000,942.170000,2414323.0
2017-05-18,943.200,954.1800,941.2700,950.500,1758452.0,0.0,1.0,943.200000,954.180000,941.270000,950.500000,1758452.0
2017-05-19,952.820,959.5600,952.0000,954.650,1327354.0,0.0,1.0,952.820000,959.560000,952.000000,954.650000,1327354.0
2017-05-22,957.000,964.8200,956.5600,964.070,1305246.0,0.0,1.0,957.000000,964.820000,956.560000,964.070000,1305246.0
2017-05-23,969.960,974.5100,964.5000,970.550,1529617.0,0.0,1.0,969.960000,974.510000,964.500000,970.550000,1529617.0
2017-05-24,975.260,978.1150,971.6299,977.610,1128880.0,0.0,1.0,975.260000,978.115000,971.629900,977.610000,1128880.0
2017-05-25,979.000,995.7800,977.8200,991.860,1951402.0,0.0,1.0,979.000000,995.780000,977.820000,991.860000,1951402.0
2017-05-26,992.000,996.3900,987.3600,993.270,1622807.0,0.0,1.0,992.000000,996.390000,987.360000,993.270000,1622807.0
2017-05-30,992.500,997.6200,991.3601,996.170,1511472.0,0.0,1.0,992.500000,997.620000,991.360100,996.170000,1511472.0
2017-05-31,996.210,999.6000,981.6800,987.090,1703990.0,0.0,1.0,996.210000,999.600000,981.680000,987.090000,1703990.0
2017-06-01,990.960,993.1400,981.2900,988.290,1295552.0,0.0,1.0,990.960000,993.140000,981.290000,988.290000,1295552.0
2017-06-02,988.590,996.4800,987.0700,996.120,1719720.0,0.0,1.0,988.590000,996.480000,987.070000,996.120000,1719720.0
2017-06-05,997.890,1007.4000,995.4500,1003.880,1353264.0,0.0,1.0,997.890000,1007.400000,995.450000,1003.880000,1353264.0
2017-06-06,1003.310,1008.6100,994.8000,996.680,1517356.0,0.0,1.0,1003.310000,1008.610000,994.800000,996.680000,1517356.0
2017-06-07,998.820,1003.9100,995.8100,1001.590,1348198.0,0.0,1.0,998.820000,1003.910000,995.810000,1001.590000,1348198.0
2017-06-08,1004.230,1005.6000,996.6200,1004.280,1657881.0,0.0,1.0,1004.230000,1005.600000,996.620000,1004.280000,1657881.0
2017-06-09,1005.490,1005.5000,953.3700,970.120,3613964.0,0.0,1.0,1005.490000,1005.500000,953.370000,970.120000,3613964.0
2017-06-12,958.720,968.0000,936.7950,961.810,4167184.0,0.0,1.0,958.720000,968.000000,936.795000,961.810000,4167184.0
2017-06-13,972.040,977.9100,962.0100,970.500,1992456.0,0.0,1.0,972.040000,977.910000,962.010000,970.500000,1992456.0
2017-06-14,975.500,979.7000,959.5103,967.930,1489046.0,0.0,1.0,975.500000,979.700000,959.510300,967.930000,1489046.0
2017-06-15,948.020,960.6775,940.3700,960.180,2349212.0,0.0,1.0,948.020000,960.677500,940.370000,960.180000,2349212.0
2017-06-16,957.910,959.9500,948.7000,958.620,2484914.0,0.0,1.0,957.910000,959.950000,948.700000,958.620000,2484914.0

In [4]:
df.describe()

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
count,3230.000000,3230.000000,3230.000000,3230.000000,3.230000e+03,3230.000000,3230.0,3230.000000,3230.000000,3230.000000,3230.000000,3.230000e+03
mean,570.808186,576.100830,564.956712,570.566407,8.184781e+06,0.175843,1.0,372.172566,375.474696,368.480699,372.022133,8.184781e+06
std,206.271015,206.836971,205.366282,206.180941,8.349518e+06,9.993679,0.0,214.286981,215.399513,212.864128,214.237958,8.349518e+06
min,99.090000,101.740000,95.960000,100.010000,5.211410e+05,0.000000,1.0,49.698414,51.027517,48.128568,50.159839,5.211410e+05
25%,451.540000,457.237500,446.130000,450.465000,2.921750e+06,0.000000,1.0,226.469088,229.326659,223.755712,225.929924,2.921750e+06
50%,553.805000,558.805000,547.600000,553.670000,5.402300e+06,0.000000,1.0,293.365591,295.289029,289.960079,292.402619,5.402300e+06
75%,690.605000,697.247500,682.396775,691.417500,1.082905e+07,0.000000,1.0,539.547500,543.896250,534.831750,539.610000,1.082905e+07
max,1226.800000,1228.880000,1218.600000,1220.170000,8.215110e+07,567.971668,1.0,1005.490000,1008.610000,996.620000,1004.280000,8.215110e+07

In [5]:
df.shape
df.tail()
#create new y
#drop split ratio
#add percentage change in opening and close
#remove high
#add percentage change between high and low
#use adj high and adj low

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2017-06-12,958.72,968.0000,936.7950,961.81,4167184.0,0.0,1.0,958.72,968.0000,936.7950,961.81,4167184.0
2017-06-13,972.04,977.9100,962.0100,970.50,1992456.0,0.0,1.0,972.04,977.9100,962.0100,970.50,1992456.0
2017-06-14,975.50,979.7000,959.5103,967.93,1489046.0,0.0,1.0,975.50,979.7000,959.5103,967.93,1489046.0
2017-06-15,948.02,960.6775,940.3700,960.18,2349212.0,0.0,1.0,948.02,960.6775,940.3700,960.18,2349212.0
2017-06-16,957.91,959.9500,948.7000,958.62,2484914.0,0.0,1.0,957.91,959.9500,948.7000,958.62,2484914.0

In [6]:
del df['Split Ratio']

In [7]:
df

,Open,High,Low,Close,Volume,Ex-Dividend,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,
2004-08-19,100.010,104.0600,95.9600,100.335,44659000.0,0.0,50.159839,52.191109,48.128568,50.322842,44659000.0
2004-08-20,101.010,109.0800,100.5000,108.310,22834300.0,0.0,50.661387,54.708881,50.405597,54.322689,22834300.0
2004-08-23,110.760,113.4800,109.0500,109.400,18256100.0,0.0,55.551482,56.915693,54.693835,54.869377,18256100.0
2004-08-24,111.240,111.6000,103.5700,104.870,15247300.0,0.0,55.792225,55.972783,51.945350,52.597363,15247300.0
2004-08-25,104.760,108.0000,103.8800,106.000,9188600.0,0.0,52.542193,54.167209,52.100830,53.164113,9188600.0
2004-08-26,104.950,107.9500,104.6600,107.910,7094800.0,0.0,52.637487,54.142132,52.492038,54.122070,7094800.0
2004-08-27,108.100,108.6200,105.6900,106.150,6211700.0,0.0,54.217364,54.478169,53.008633,53.239345,6211700.0
2004-08-30,105.280,105.4900,102.0100,102.010,5196700.0,0.0,52.802998,52.908323,51.162935,51.162935,5196700.0
2004-08-31,102.320,103.7100,102.1600,102.370,4917800.0,0.0,51.318415,52.015567,51.238167,51.343492,4917800.0
2004-09-01,102.700,102.9700,99.6700,100.250,9138200.0,0.0,51.509003,51.644421,49.989312,50.280210,9138200.0
2004-09-02,99.090,102.3700,98.9400,101.510,15118600.0,0.0,49.698414,51.343492,49.623182,50.912161,15118600.0
2004-09-03,100.950,101.7400,99.3200,100.010,5152400.0,0.0,50.631294,51.027517,49.813770,50.159839,5152400.0
2004-09-07,101.010,102.0000,99.6100,101.580,5847500.0,0.0,50.661387,51.157920,49.959219,50.947269,5847500.0
2004-09-08,100.740,103.0300,100.5000,102.300,4985600.0,0.0,50.525969,51.674514,50.405597,51.308384,4985600.0
2004-09-09,102.500,102.7100,101.0000,102.310,4061700.0,0.0,51.408694,51.514019,50.656371,51.313400,4061700.0
2004-09-10,101.470,106.5600,101.3000,105.330,8698800.0,0.0,50.892099,53.444980,50.806836,52.828075,8698800.0
2004-09-13,106.630,108.4100,106.4600,107.500,7844100.0,0.0,53.480088,54.372844,53.394825,53.916435,7844100.0
2004-09-14,107.440,112.0000,106.7900,111.490,10828900.0,0.0,53.886342,56.173402,53.560336,55.917612,10828900.0
2004-09-15,110.560,114.2300,110.2000,112.000,10713000.0,0.0,55.451172,57.291854,55.270615,56.173402,10713000.0
2004-09-16,112.340,115.8000,111.6500,113.970,9266300.0,0.0,56.343928,58.079285,55.997860,57.161452,9266300.0
2004-09-17,114.420,117.4900,113.5500,117.490,9472500.0,0.0,57.387149,58.926902,56.950802,58.926902,9472500.0
2004-09-20,116.950,121.6000,116.7700,119.360,10628700.0,0.0,58.656066,60.988265,58.565787,59.864797,10628700.0
2004-09-21,120.200,120.4200,117.5100,117.840,7228700.0,0.0,60.286097,60.396438,58.936933,59.102444,7228700.0
2004-09-22,117.450,119.6700,116.8100,118.380,7581200.0,0.0,58.906840,60.020277,58.585849,59.373280,7581200.0
2004-09-23,118.840,122.6300,117.0200,120.820,8535600.0,0.0,59.603992,61.504860,58.691174,60.597057,8535600.0
2004-09-24,120.970,124.1000,119.7600,119.830,9123400.0,0.0,60.672290,62.242136,60.065416,60.100525,9123400.0
2004-09-27,119.560,120.8800,117.8000,118.260,7066100.0,0.0,59.965107,60.627150,59.082382,59.313094,7066100.0
2004-09-28,121.150,127.4000,120.2100,126.860,16929000.0,0.0,60.762568,63.897245,60.291113,63.626409,16929000.0
2004-09-29,126.530,135.0200,126.2300,131.080,30516400.0,0.0,63.460898,67.719042,63.310433,65.742942,30516400.0
2004-09-30,129.899,132.3000,129.0000,129.600,13758000.0,0.0,65.150614,66.354831,64.699722,65.000651,13758000.0
...,...,...,...,...,...,...,...,...,...,...,...
2017-05-05,956.720,958.4395,948.0986,950.280,1593898.0,0.0,956.720000,958.439500,948.098600,950.280000,1593898.0
2017-05-08,947.450,960.9900,947.3950,958.690,1863198.0,0.0,947.450000,960.990000,947.395000,958.690000,1863198.0
2017-05-09,961.330,962.2000,954.4000,956.710,1633396.0,0.0,961.330000,962.200000,954.400000,956.710000,1633396.0
2017-05-10,956.220,956.7100,949.8400,954.840,1135809.0,0.0,956.220000,956.710000,949.840000,954.840000,1135809.0
2017-05-11,951.290,957.9900,948.6100,955.890,1016797.0,0.0,951.290000,957.990000,948.610000,955.890000,1016797.0
2017-05-12,957.850,957.9800,952.0600,955.140,1204133.0,0.0,957.850000,957.980000,952.060000,955.140000,1204133.0
2017-05-15,955.290,962.7000,952.8200,959.220,1314574.0,0.0,955.290000,962.700000,952.820000,959.220000,1314574.0
2017-05-16,963.550,965.8955,960.3500,964.610,1069898.0,0.0,963.550000,965.895500,960.350000,964.610000,1069898.0
2017-05-17,959.700,960.9900,940.0600,942.170,2414323.0,0.0,959.700000,960.990000,940.060000,942.170000,2414323.0
2017-05-18,943.200,954.1800,941.2700,950.500,1758452.0,0.0,943.200000,954.180000,941.270000,950.500000,1758452.0
2017-05-19,952.820,959.5600,952.0000,954.650,1327354.0,0.0,952.820000,959.560000,952.000000,954.650000,1327354.0
2017-05-22,957.000,964.8200,956.5600,964.070,1305246.0,0.0,957.000000,964.820000,956.560000,964.070000,1305246.0
2017-05-23,969.960,974.5100,964.5000,970.550,1529617.0,0.0,969.960000,974.510000,964.500000,970.550000,1529617.0
2017-05-24,975.260,978.1150,971.6299,977.610,1128880.0,0.0,975.260000,978.115000,971.629900,977.610000,1128880.0
2017-05-25,979.000,995.7800,977.8200,991.860,1951402.0,0.0,979.000000,995.780000,977.820000,991.860000,1951402.0
2017-05-26,992.000,996.3900,987.3600,993.270,1622807.0,0.0,992.000000,996.390000,987.360000,993.270000,1622807.0
2017-05-30,992.500,997.6200,991.3601,996.170,1511472.0,0.0,992.500000,997.620000,991.360100,996.170000,1511472.0
2017-05-31,996.210,999.6000,981.6800,987.090,1703990.0,0.0,996.210000,999.600000,981.680000,987.090000,1703990.0
2017-06-01,990.960,993.1400,981.2900,988.290,1295552.0,0.0,990.960000,993.140000,981.290000,988.290000,1295552.0
2017-06-02,988.590,996.4800,987.0700,996.120,1719720.0,0.0,988.590000,996.480000,987.070000,996.120000,1719720.0
2017-06-05,997.890,1007.4000,995.4500,1003.880,1353264.0,0.0,997.890000,1007.400000,995.450000,1003.880000,1353264.0
2017-06-06,1003.310,1008.6100,994.8000,996.680,1517356.0,0.0,1003.310000,1008.610000,994.800000,996.680000,1517356.0
2017-06-07,998.820,1003.9100,995.8100,1001.590,1348198.0,0.0,998.820000,1003.910000,995.810000,1001.590000,1348198.0
2017-06-08,1004.230,1005.6000,996.6200,1004.280,1657881.0,0.0,1004.230000,1005.600000,996.620000,1004.280000,1657881.0
2017-06-09,1005.490,1005.5000,953.3700,970.120,3613964.0,0.0,1005.490000,1005.500000,953.370000,970.120000,3613964.0
2017-06-12,958.720,968.0000,936.7950,961.810,4167184.0,0.0,958.720000,968.000000,936.795000,961.810000,4167184.0
2017-06-13,972.040,977.9100,962.0100,970.500,1992456.0,0.0,972.040000,977.910000,962.010000,970.500000,1992456.0
2017-06-14,975.500,979.7000,959.5103,967.930,1489046.0,0.0,975.500000,979.700000,959.510300,967.930000,1489046.0
2017-06-15,948.020,960.6775,940.3700,960.180,2349212.0,0.0,948.020000,960.677500,940.370000,960.180000,2349212.0
2017-06-16,957.910,959.9500,948.7000,958.620,2484914.0,0.0,957.910000,959.950000,948.700000,958.620000,2484914.0

In [8]:
del df['Open']
del df['High']
del df['Low']
del df['Close']
del df['Volume']

In [10]:
del df['Ex-Dividend']
df

              Adj. Open    Adj. High    Adj. Low   Adj. Close  Adj. Volume
Date
2004-08-19    50.159839    52.191109   48.128568    50.322842   44659000.0
2004-08-20    50.661387    54.708881   50.405597    54.322689   22834300.0
2004-08-23    55.551482    56.915693   54.693835    54.869377   18256100.0
2004-08-24    55.792225    55.972783   51.945350    52.597363   15247300.0
2004-08-25    52.542193    54.167209   52.100830    53.164113    9188600.0
2004-08-26    52.637487    54.142132   52.492038    54.122070    7094800.0
2004-08-27    54.217364    54.478169   53.008633    53.239345    6211700.0
2004-08-30    52.802998    52.908323   51.162935    51.162935    5196700.0
2004-08-31    51.318415    52.015567   51.238167    51.343492    4917800.0
2004-09-01    51.509003    51.644421   49.989312    50.280210    9138200.0
2004-09-02    49.698414    51.343492   49.623182    50.912161   15118600.0
2004-09-03    50.631294    51.027517   49.813770    50.159839    5152400.0
2004-09-07    50.661387    51.157920   49.959219    50.947269    5847500.0
2004-09-08    50.525969    51.674514   50.405597    51.308384    4985600.0
2004-09-09    51.408694    51.514019   50.656371    51.313400    4061700.0
2004-09-10    50.892099    53.444980   50.806836    52.828075    8698800.0
2004-09-13    53.480088    54.372844   53.394825    53.916435    7844100.0
2004-09-14    53.886342    56.173402   53.560336    55.917612   10828900.0
2004-09-15    55.451172    57.291854   55.270615    56.173402   10713000.0
2004-09-16    56.343928    58.079285   55.997860    57.161452    9266300.0
2004-09-17    57.387149    58.926902   56.950802    58.926902    9472500.0
2004-09-20    58.656066    60.988265   58.565787    59.864797   10628700.0
2004-09-21    60.286097    60.396438   58.936933    59.102444    7228700.0
2004-09-22    58.906840    60.020277   58.585849    59.373280    7581200.0
2004-09-23    59.603992    61.504860   58.691174    60.597057    8535600.0
2004-09-24    60.672290    62.242136   60.065416    60.100525    9123400.0
2004-09-27    59.965107    60.627150   59.082382    59.313094    7066100.0
2004-09-28    60.762568    63.897245   60.291113    63.626409   16929000.0
2004-09-29    63.460898    67.719042   63.310433    65.742942   30516400.0
2004-09-30    65.150614    66.354831   64.699722    65.000651   13758000.0
...                 ...          ...         ...          ...          ...
2017-05-05   956.720000   958.439500  948.098600   950.280000    1593898.0
2017-05-08   947.450000   960.990000  947.395000   958.690000    1863198.0
2017-05-09   961.330000   962.200000  954.400000   956.710000    1633396.0
2017-05-10   956.220000   956.710000  949.840000   954.840000    1135809.0
2017-05-11   951.290000   957.990000  948.610000   955.890000    1016797.0
2017-05-12   957.850000   957.980000  952.060000   955.140000    1204133.0
2017-05-15   955.290000   962.700000  952.820000   959.220000    1314574.0
2017-05-16   963.550000   965.895500  960.350000   964.610000    1069898.0
2017-05-17   959.700000   960.990000  940.060000   942.170000    2414323.0
2017-05-18   943.200000   954.180000  941.270000   950.500000    1758452.0
2017-05-19   952.820000   959.560000  952.000000   954.650000    1327354.0
2017-05-22   957.000000   964.820000  956.560000   964.070000    1305246.0
2017-05-23   969.960000   974.510000  964.500000   970.550000    1529617.0
2017-05-24   975.260000   978.115000  971.629900   977.610000    1128880.0
2017-05-25   979.000000   995.780000  977.820000   991.860000    1951402.0
2017-05-26   992.000000   996.390000  987.360000   993.270000    1622807.0
2017-05-30   992.500000   997.620000  991.360100   996.170000    1511472.0
2017-05-31   996.210000   999.600000  981.680000   987.090000    1703990.0
2017-06-01   990.960000   993.140000  981.290000   988.290000    1295552.0
2017-06-02   988.590000   996.480000  987.070000   996.120000    1719720.0
2017-06-05   997.890000  1007.400000  995.450000  1003.880000    1353264.0
2017-06-06  1003.310000  1008.610000  994.800000   996.680000    1517356.0
2017-06-07   998.820000  1003.910000  995.810000  1001.590000    1348198.0
2017-06-08  1004.230000  1005.600000  996.620000  1004.280000    1657881.0
2017-06-09  1005.490000  1005.500000  953.370000   970.120000    3613964.0
2017-06-12   958.720000   968.000000  936.795000   961.810000    4167184.0
2017-06-13   972.040000   977.910000  962.010000   970.500000    1992456.0
2017-06-14   975.500000   979.700000  959.510300   967.930000    1489046.0
2017-06-15   948.020000   960.677500  940.370000   960.180000    2349212.0
2017-06-16   957.910000   959.950000  948.700000   958.620000    2484914.0

[3230 rows x 5 columns]

In [11]:
df.reset_index(drop = True, inplace = True)

In [12]:
df['Target']= df[0:len(df)-5]['Adj. Open']

df

,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume,Target
0,50.159839,52.191109,48.128568,50.322842,44659000.0,50.159839
1,50.661387,54.708881,50.405597,54.322689,22834300.0,50.661387
2,55.551482,56.915693,54.693835,54.869377,18256100.0,55.551482
3,55.792225,55.972783,51.945350,52.597363,15247300.0,55.792225
4,52.542193,54.167209,52.100830,53.164113,9188600.0,52.542193
5,52.637487,54.142132,52.492038,54.122070,7094800.0,52.637487
6,54.217364,54.478169,53.008633,53.239345,6211700.0,54.217364
7,52.802998,52.908323,51.162935,51.162935,5196700.0,52.802998
8,51.318415,52.015567,51.238167,51.343492,4917800.0,51.318415
9,51.509003,51.644421,49.989312,50.280210,9138200.0,51.509003
10,49.698414,51.343492,49.623182,50.912161,15118600.0,49.698414
11,50.631294,51.027517,49.813770,50.159839,5152400.0,50.631294
12,50.661387,51.157920,49.959219,50.947269,5847500.0,50.661387
13,50.525969,51.674514,50.405597,51.308384,4985600.0,50.525969
14,51.408694,51.514019,50.656371,51.313400,4061700.0,51.408694
15,50.892099,53.444980,50.806836,52.828075,8698800.0,50.892099
16,53.480088,54.372844,53.394825,53.916435,7844100.0,53.480088
17,53.886342,56.173402,53.560336,55.917612,10828900.0,53.886342
18,55.451172,57.291854,55.270615,56.173402,10713000.0,55.451172
19,56.343928,58.079285,55.997860,57.161452,9266300.0,56.343928
20,57.387149,58.926902,56.950802,58.926902,9472500.0,57.387149
21,58.656066,60.988265,58.565787,59.864797,10628700.0,58.656066
22,60.286097,60.396438,58.936933,59.102444,7228700.0,60.286097
23,58.906840,60.020277,58.585849,59.373280,7581200.0,58.906840
24,59.603992,61.504860,58.691174,60.597057,8535600.0,59.603992
25,60.672290,62.242136,60.065416,60.100525,9123400.0,60.672290
26,59.965107,60.627150,59.082382,59.313094,7066100.0,59.965107
27,60.762568,63.897245,60.291113,63.626409,16929000.0,60.762568
28,63.460898,67.719042,63.310433,65.742942,30516400.0,63.460898
29,65.150614,66.354831,64.699722,65.000651,13758000.0,65.150614
...,...,...,...,...,...,...
3200,956.720000,958.439500,948.098600,950.280000,1593898.0,956.720000
3201,947.450000,960.990000,947.395000,958.690000,1863198.0,947.450000
3202,961.330000,962.200000,954.400000,956.710000,1633396.0,961.330000
3203,956.220000,956.710000,949.840000,954.840000,1135809.0,956.220000
3204,951.290000,957.990000,948.610000,955.890000,1016797.0,951.290000
3205,957.850000,957.980000,952.060000,955.140000,1204133.0,957.850000
3206,955.290000,962.700000,952.820000,959.220000,1314574.0,955.290000
3207,963.550000,965.895500,960.350000,964.610000,1069898.0,963.550000
3208,959.700000,960.990000,940.060000,942.170000,2414323.0,959.700000
3209,943.200000,954.180000,941.270000,950.500000,1758452.0,943.200000
3210,952.820000,959.560000,952.000000,954.650000,1327354.0,952.820000
3211,957.000000,964.820000,956.560000,964.070000,1305246.0,957.000000
3212,969.960000,974.510000,964.500000,970.550000,1529617.0,969.960000
3213,975.260000,978.115000,971.629900,977.610000,1128880.0,975.260000
3214,979.000000,995.780000,977.820000,991.860000,1951402.0,979.000000
3215,992.000000,996.390000,987.360000,993.270000,1622807.0,992.000000
3216,992.500000,997.620000,991.360100,996.170000,1511472.0,992.500000
3217,996.210000,999.600000,981.680000,987.090000,1703990.0,996.210000
3218,990.960000,993.140000,981.290000,988.290000,1295552.0,990.960000
3219,988.590000,996.480000,987.070000,996.120000,1719720.0,988.590000
3220,997.890000,1007.400000,995.450000,1003.880000,1353264.0,997.890000
3221,1003.310000,1008.610000,994.800000,996.680000,1517356.0,1003.310000
3222,998.820000,1003.910000,995.810000,1001.590000,1348198.0,998.820000
3223,1004.230000,1005.600000,996.620000,1004.280000,1657881.0,1004.230000
3224,1005.490000,1005.500000,953.370000,970.120000,3613964.0,1005.490000
3225,958.720000,968.000000,936.795000,961.810000,4167184.0,NaN
3226,972.040000,977.910000,962.010000,970.500000,1992456.0,NaN
3227,975.500000,979.700000,959.510300,967.930000,1489046.0,NaN
3228,948.020000,960.677500,940.370000,960.180000,2349212.0,NaN
3229,957.910000,959.950000,948.700000,958.620000,2484914.0,NaN

In [13]:
df.dropna(axis = 0, inplace = True)

df.shape
df.tail()

      Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume   Target
3220     997.89    1007.40    995.45     1003.88    1353264.0   997.89
3221    1003.31    1008.61    994.80      996.68    1517356.0  1003.31
3222     998.82    1003.91    995.81     1001.59    1348198.0   998.82
3223    1004.23    1005.60    996.62     1004.28    1657881.0  1004.23
3224    1005.49    1005.50    953.37      970.12    3613964.0  1005.49

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
from sklearn import cross_validation
clf = LinearRegression()
array = df.values
X = array[:,0:6]
Y = ['Target']

C:\Users\SOMYAA\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [130]:
s = 7

In [16]:
X_Train, X_Test, Y_Train, Y_Test = cross_validation.train_test_split(X, df['Target'], test_size = 0.25)

In [20]:
clf.fit(X_Train,Y_Train)
Predict = clf.predict(X_Test)
score = clf.score(X_Test,Y_Test)
score

1.0

In [146]:
#apply feature scaling
X_Scaled = preprocessing.scale(X)

#change = adj open- target/adj open*100